---
version: "3.8"

services:
  proxy:
    image: "el9.2-java17-velocity:3.2.0-265"
    container_name: "proxy"
    environment:
      - MEMORYSIZE: 1G
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    networks:
      - minecraft
    restart: unless-stopped
    volumes:
      - "/home/ikrell/server/proxy:/proxy:rw,Z"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2048M"

  slave01:
    image: "el9.2-java17-multipaper:1.20.1-911ff8e"
    container_name: "slave01"
    environment:
      - MEMORYSIZE: 2G
      - SERVERNAME: slave01
      - MASTERIP: proxy
    stdin_open: true
    tty: true
    networks:
      - minecraft
    restart: unless-stopped
    volumes:
      - "/home/ikrell/server/slave01:/server:rw,Z"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "3072M"

  slave02:
    image: "el9.2-java17-multipaper:1.20.1-911ff8e"
    container_name: "slave02"
    environment:
      - MEMORYSIZE: 2G
      - SERVERNAME: slave02
      - MASTERIP: proxy
    stdin_open: true
    tty: true
    networks:
      - minecraft
    restart: unless-stopped
    volumes:
      - "/home/ikrell/server/slave02:/server:rw,Z"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "3072M"

networks:
  minecraft: