---
version: "3.8"

services:
  proxy:
    image: "el9.2-java17-velocity:3.2.0-265"
    container_name: "proxy"
    environment:
      - MEMORYSIZE: 1G
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    networks:
      - minecraft
    restart: unless-stopped
    volumes:
      - "/home/ikrell/server/proxy:/proxy:rw,Z"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2048M"

  main:
    image: "el9.2-java17-kaiiju:1.20.1-236"
    container_name: "main"
    environment:
      - MEMORYSIZE: 6G
    stdin_open: true
    tty: true
    networks:
      - minecraft
    restart: unless-stopped
    volumes:
      - "/home/ikrell/server/main:/server:rw,Z"
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: "7168M"

networks:
  minecraft: