---
version: "3.8"

services:
  proxy:
    image: "el9.2-java17-velocity:3.2.0-265"
    container_name: "proxy"
    environment:
      - MEMORYSIZE: 8G
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    networks:
      - minecraft
    restart: unless-stopped
    volumes:
      - "/home/ikrell/server/proxy:/proxy:rw,Z"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "16G"

  main:
    image: "el9.2-java17-purpur:1.20.1-2051"
    container_name: "main"
    environment:
      - MEMORYSIZE: 24G
    stdin_open: true
    tty: true
    networks:
      - minecraft
    restart: unless-stopped
    volumes:
      - "/home/ikrell/server/main:/server:rw,Z"
    deploy:
      resources:
        limits:
          cpus: "12"
          memory: "32G"

networks:
  minecraft: