name: Docker Image CI

on:
  push:
    branches: [ "dionysus" ]
  pull_request:
    branches: [ "dionysus" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag docker.io/rickaurman/el9.2-java17-dionysus-1.12.2:latest --file Dionysus/Dockerfile .
    - name: Push the Docker image
      run: docker login -u rickaurman -p ${{ secrets.DOCKER_TOKEN }} && docker push docker.io/rickaurman/el9.2-java17-dionysus-1.12.2:latest
