name: Trigger action in other repository

on:
  milestone:
    - repository: https://github.com/WolfAURman/test.git
      branch: main
      event: commit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: echo "New commit detected!"
